export const {
    PORT,
    ORIGIN,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_PASS,
    FROM_EMAIL,
    NODE_ENV,
    PASSWORD_RESET_SECRET,
    KHALTI_SECRET_KEY,
    KHALTI_GATEWAY_URL
} = process.env