-- DropForeignKey
ALTER TABLE `rental` DROP FOREIGN KEY `Rental_id_fkey`;

-- AlterTable
ALTER TABLE `furniture` MODIFY `category` ENUM('SOFA', 'BED', 'TABLE', 'CHAIR', 'WARDROBE', 'DESK', 'BOOKSHELF', 'DRESSER', 'NIGHTSTAND', 'CABINET', 'OTTOMAN', 'RECLINER', 'BENCH', 'HUTCH', 'TV_STAND', 'DINING_SET', 'ENTRYWAY', 'STORAGE', 'KITCHEN_ISLAND', 'VANITY', 'SECTIONAL', 'LOVESEAT', 'FILING_CABINET', 'OTHER') NOT NULL;

-- AddForeignKey
ALTER TABLE `RentToOwnAgreement` ADD CONSTRAINT `RentToOwnAgreement_rentalId_fkey` FOREIGN KEY (`rentalId`) REFERENCES `Rental`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
